
# ======================================================== #
# File automagically generated by GUI2Exe version 0.5.3
# Copyright: (c) 2007-2012 Andrea Gavana
# ======================================================== #

# Let's start with some default (for me) imports...

from distutils.core import setup
from py2exe.build_exe import py2exe

import glob
import os
import zlib
import shutil

# Remove the build folder
shutil.rmtree("build", ignore_errors=True)


class Target(object):
    """ A simple class that holds information on our executable file. """
    def __init__(self, **kw):
        """ Default class constructor. Update as you need. """
        self.__dict__.update(kw)
        

# Ok, let's explain why I am doing that.
# Often, data_files, excludes and dll_excludes (but also resources)
# can be very long list of things, and this will clutter too much
# the setup call at the end of this file. So, I put all the big lists
# here and I wrap them using the textwrap module.

data_files = [('Textures', ['F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Acceleration.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\BackButton.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Background.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\BackPressed.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Cursor2.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Enemy.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\ExitButton.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\ExitPressed.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Friction.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Icon.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Iconsmall.ico',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Iconsmall.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\largeParticle.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Maxspeed.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\OptionsButton.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\OptionsMeter.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\OptionsPressed.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\PlayButton.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\PlayPressed.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Projectile.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Slider.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\smallParticle.png',
                            'F:\\Portable Python 2.7.3.1\\Specular\\Textures\\Title.png']),
              ('Player', ['F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame0.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame1.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame10.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame11.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame12.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame13.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame14.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame15.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame16.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame17.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame18.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame19.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame2.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame20.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame21.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame22.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame23.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame24.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame25.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame26.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame27.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame28.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame29.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame3.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame30.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame31.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame32.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame33.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame34.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame35.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame36.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame37.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame38.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame39.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame4.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame40.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame5.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame6.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame7.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame8.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Frame9.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Middle.png',
                          'F:\\Portable Python 2.7.3.1\\Specular\\Player\\Shadow.png']),
              ('Audio', ['F:\\Portable Python 2.7.3.1\\Specular\\Audio\\02.mp3',
                         'F:\\Portable Python 2.7.3.1\\Specular\\Audio\\04.mp3'])]

includes = []
excludes = ['_gtkagg', '_tkagg', 'bsddb', 'curses', 'email', 'pywin.debugger',
            'pywin.debugger.dbgcon', 'pywin.dialogs', 'tcl',
            'Tkconstants', 'Tkinter']
packages = []
dll_excludes = ['libgdk-win32-2.0-0.dll', 'libgobject-2.0-0.dll', 'tcl84.dll',
                'tk84.dll']
icon_resources = []
bitmap_resources = []
other_resources = []


# This is a place where the user custom code may go. You can do almost
# whatever you want, even modify the data_files, includes and friends
# here as long as they have the same variable name that the setup call
# below is expecting.

# No custom code added


# Ok, now we are going to build our target class.
# I chose this building strategy as it works perfectly for me :-D

GUI2Exe_Target_1 = Target(
    # what to build
    script = "Specular.py",
    icon_resources = icon_resources,
    bitmap_resources = bitmap_resources,
    other_resources = other_resources,
    dest_base = "Specular",    
    version = "0.1",
    company_name = "McDrang",
    copyright = "No Copyrights",
    name = "Specular",
    
    )

# No custom class for UPX compression or Inno Setup script

# That's serious now: we have all (or almost all) the options py2exe
# supports. I put them all even if some of them are usually defaulted
# and not used. Some of them I didn't even know about.
                    
setup(

    # No UPX or Inno Setup

    data_files = data_files,

    options = {"py2exe": {"compressed": 1, 
                          "optimize": 2,
                          "includes": includes,
                          "excludes": excludes,
                          "packages": packages,
                          "dll_excludes": dll_excludes,
                          "bundle_files": 2,
                          "dist_dir": "dist",
                          "xref": False,
                          "skip_archive": False,
                          "ascii": False,
                          "custom_boot_script": '',
                         }
              },

    zipfile = None,
    console = [],
    windows = [GUI2Exe_Target_1],
    service = [],
    com_server = [],
    ctypes_com_server = []
    )

# This is a place where any post-compile code may go.
# You can add as much code as you want, which can be used, for example,
# to clean up your folders or to do some particular post-compilation
# actions.

# No post-compilation code added


# And we are done. That's a setup script :-D

